Better player animations
lee17017/Destruction4Dummies pull request #60
Opened 2019-12-25 17:02 UTC by JonlineRB

Smoothed out a lot of transitions.

Elevated player's respawn at start platform slightly.

Replaced the end of level jumping with a silly dance.

2019-12-25 20:57 UTC, lee17017 requested changes
Set the x and z-Scale of the model to same value. Currently looks really weird when it looks at me.

2019-12-25 20:57 UTC, lee17017 commented on Assets/Scripts/Input/Player.cs
> +                animator.SetBool("isDancing", true);
Is currently not  working.
Also this does not need to be in the loop(had the loop only so that they would keep continuesly jumping)

2019-12-25 20:57 UTC, lee17017 commented on Assets/Scripts/Input/Player.cs
> +                transform.GetChild(0).transform.eulerAngles = new Vector3(0, lookAtCrowd, 0);
Use a [SerializeField] for this instead of GetChild - just in case we need to add a child

2019-12-26 16:03 UTC, MarcoTUM approved these changes

2019-12-26 18:52 UTC, lee17017 approved these changes
Nice Dance :)

2019-12-29 12:00 UTC, merged